
- name: Disabling selinux
  selinux:
    state: disabled

- name: stop and disable firewalld
  service: 
    name: firewalld
    state: stopped
    enabled: no

- name: "Add EPEL repo"
  yum_repository:
    name: nginx-stable
    description: nginx repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgkey: https://nginx.org/keys/nginx_signing.key

- name: Install nginx server
  yum:
    name: nginx
    state: present

- name: start and enable nginx server
  service:
    name: nginx
    state: started
    enabled: yes

    #- name: create sites-available dir
    #  file:
    #    path: "{{ nginx_sites_avail }}"
    #    state: directory
    #    mode: 755

- name: copy ssl.conf to the nginx server
  template:
    src: ssl.conf
    dest: "{{ nginx_confd }}"
  notify: restart nginx

  #- name: copy nginx-tomcat.conf to the sites-available dir
  #  copy:
  # src: nginx-tomcat.conf
  # dest: "{{ nginx_sites_avail }}"


####### Create the SSL cert and keys #######
#
- name: install openssl
  yum:
    name: openssl
    state: present

- name: create private dir
  file:
    path: /etc/ssl/private
    state: directory
    mode: 0700

- name: generate self-signed SSL certificate
  command:
    openssl req -x509 -subj "{{ nginx_ssl_certificate_subject }}" -nodes -days {{ nginx_ssl_certificate_days }} -newkey rsa:2048 -keyout {{ nginx_ssl_certificate_key }} -out {{ nginx_ssl_certificate }}
  args:
    creates: "{{ nginx_ssl_certificate }}"
  notify: restart nginx
